### ISSUE TITLE
Job timeout because monitoring fails to read files

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#321]
**Bug Description**
During test case execution, sometimes the following error occurs:
```
Traceback (most recent call last):
  File "/Users/heikoaydt/Desktop/repositories/saas-middleware/saas/rti/adapters/base.py", line 66, in run_command
    result = subprocess.run(wrapped_command, capture_output=True, check=check_exitcode, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'cat /Users/heikoaydt/testing/1665623714998/node/jobs/JdvkjRzM/execute_sh.pid']' returned non-zero exit status 1.
```
If this happens, the state of the job is forever `State.TIMEOUT`:
```
state=<State.TIMEOUT: 'timeout'> progress=0 output={} notes={'requests': [{'req_id': 'P5IQ1lOIczW6Bpse', 'receiver': 'byxfwaa7lp0079xe9m0os6izz0onjxe5l4ova2f7hfxlk3o7t70ug58jdoijfcgf', 'request': 'T1ShSyxcV2OAjWfZkT7p3HO9bPd2jhKDFlgPArWw21VphRfeFj6/N57rMX3kFJPDE5VgYWWLiqQV+QIEI7PrRPuMx5t+hcPCPi7FQlod3PWB4PNvaUybDa1gj+sBO8NOIDzQxkTQqBGLE+NlLJbSAAZNwrV3xENs/Jz6yPQ6yYV+f7hQjWDn1tztzOcWxWz0gV0KkBOUwhyheG/v5iWX8k/t3vCxOVOhGcf1z+2A7qVp2gf4bVzC29+CBb4nRcjOJUS6LmckfI26s6H8rTTM8qtbrIy/O1rxkMySKg1XaY2RE9Tq5r6KZk8Y5xVqwpDsvnqCG3uFwlxOAufzzOIVzRVaiT7V2yBmtpTJ9rgVAHHr+2HfQSBBUKBQ3/L5/1uR1gKRYHYiq7CVcqb2+c8EwbEqFFc8f4DUzsbL1H+EIuPg9UuAVDvpGtWiVFbXENZUkNmICkZAV6eLWHv/sV5JnLPS4nEiMl2xN/ZGJuj5jtrCTSdKUwonGiEKzqdKPfwyAoggy1iX0EwXhDgirzulW0tkeUDKio6d7alcoUbglwP9qdNs/e7c2v+olDcN40u4e29wS3ocGjERA/BkFxfsndG+ws8mwj8EfL9cGs4xwSTyYl/45qC99YumOOXDr/SEYnYK4Wu57OTk6f0LL0pB7zv5VWv42yw5JgRFAEn859c/k3o+tmJExfS2SzW27z8gIsv097yweKyRQPgXQAMpvbVSceHPQpZYiOKkslslzrCB2ACy0wB+NC8pwMYJLi0KlHzMFcVx0kyWVfHdEksy8rbQmE/X+XsH5AA7HW+jlLbNs6ApSoFmZ6QKudehJ2wjuhqITOjluVkK8s92f28c/nyOv3UYv7rj2AwTqIy4nkdbykkLNAb4LZvW3Ao0GPxSFbM06SHcAsGq3JXbArBTeOnhxsL7ANmz02PxcaxbjVPkGCUYdJZ7pmUY8eL/76FPVaL99XaPuz+F+ken3tghRvd91SlhFISbh9B6K0Ad/ujGSX948/mbVaxSXbpdwVRqBr5VWHRSvhrVu5X57ERoBg/8PpekNZNjx2q9JRr7DM4X4sW+k3JU3PPfYU4HhppD5wf6Utr2uffzDR+UoDGKxbMYP/764nhIijAPU2OTDVJUXqxARTJTCVUTAjfI3XkE7VcAzeueQSxbAdRKPLJpc7Np9cmwt9ZEvt0nEVJ5gCBeVFbUdkcKh6D+K/fWHZrCHOjRGjncUMBra1XYq6Ybgh/qeqbjowtW8x/t6owO6o+8hxM9U8YpQSxCZMn7xergx0Z5FPJ7YfafG7Td6hERVtbf6Vipzsus9IxRSIO8jE/CGg2Q78VR4NB+cPwxOf2PXBPqj+AWmtH16cJxCMla5LT0IYfUA0dOg32p08Wpb882HiiQuC2WGGKjgrzYE0lbRj6tA0TDMFLu6cdpURfohnOzkwft2E2bcXlGZTjsy8IUAwkxQCqfIGJxdi9+WvRAy87gPDNPGWLKwIAYoRW/pWG4xDUo9e+hUsuu7T2WfRTDKM0GLlXkE/N0p4a4ea0pOEpeVtUkA0g2uhfCzio6vxRnwEWdMHSYY1cK07vElkqsCOfcgvn4mmfPTzd9Fp491oFEQ1C4dNjK5uSF8urTZWJ8qVb1jCVg8sDeNbeOg4KpanVuiYDyovqypQxEwZD/gOkudIq14+bCcnNckHeA+mcbCfKbYyGQQEHpiZQN/IQ05KFipzs2a+v0fYrnG4UBSnB2dyzwqBDaqzTucZmqlMXOC1SCLZy2tx3wVFS5gqrbeUJfaN+520zXn2BtKQJSbiam4EYsa3u7imnBUgVQSWiN2LyKmT2AfDwlvt2W7HhI1kflbqedLMk7JHNJI+9hMQIzjr+bUnrTQ2bBEhlOhhwfX5AHiV54DbrmxwymsV7qMlsEbWMeNl6zJIvn4TvhYnuUL+IozRTP3sojcSTXHgv2N2Ntwxs0N6Wu7+B3JTPgo2Pc/ab5hMDNhHHbAbCF+iAvbFawc0g+T5/fDtO1mPUL+fmBmliGzHMbA0isMozAlxxMljH/Y/2aBqimdapknBDW1Ot/1VfQ5/tPUOPg5JKPhk1DWTUfLvxTFGO1JGId+HLbt5YdUK4HluZomI3KZK3Z/GF0wUQ0b8ouczFmqtNyUqihNKWlCue0L7HHZGKs0rED4265gYTxyuiuw8KYe54F3xi7H89+Vbdkk2xFEq66O2LoJ7essBPwCOuT6rt14Q4VYWR1EMKRQGgJohDbIpq4vsrHxv5NSObRvSdQ+xsQyUXbWcJeYTmfzoJEQUf+iLHBfWEinjMaGthg/GTGofpo6x9oPB72ZEc88b3Mw7KN4T7OSQGk28V+U3hSsSQP8UigW3JXh9xRjMnFvGyXy9ubiO4orSoVjlqzoqV3zuStJhtfCmv1E//tR2MOHdX4fjb017SOFbDJbeccwZRaYVCF5hq6SsNmGmqShB4mtx+mBA23gLRocgcQOWmUe4MsbD9/B/iLqqDA5oKtqkWYiUGuKFWRz2gtBrL6bTh7HB+KMAhtdIO9Qeqn2gi7N7GnDgtX7UNIMqd6dpYclSKYkrg1gPjj2bFweEhULV0oi6n4CdK/RNBiLHRLdjihTwovkx/nkYyyBx/K/VqCAhSZL7ybJ+lIA2Nwx76SmTbpPMzKcnlJYse6WXHHFXvXFY5DmYq7IsxiigF/6By2UEOQzva5+HF1jZQlbk6hhqYZ2/hByI2Dv0yl+YZ53sCJDzeQ2deOwhn/OgxbStUnNk0C1YgOufxrBfUx+hu+pg7tjGL2eXMeTIfxbHPLPUuEG2lxO+FCwbqQqpfp6H+bDQ5rlj9aAvhhivIulWkuZYDFem0/GZSQwIzDmUQ6NtLpjoD2v7rP4g41QvWBduARG/6ucXghbTlkdB/2uoCZ4qYTcMkESdobYy4Wfpr5hM16Oy+XjQjdzYXZnO63zagAle/E/0r9zADyuWlIpCJI+fVQhlRKKH3oB1HdBmRTKka77uwRraldFe74B1buzvum6/8N2gi9CnLjYXYD++cbZz/1eZAMLJwWxxvO7/HlO0vYJutoIAY55wQ1JcQXJ+TEhwv4DrhXvsA6C9UCHmSsRaJEs1amY+29ML2kLnFrvuYszdxw57iy9BBWLct6/Da1BE3D+v3DK9Gyp+F8CqTL2o6/Wr7pua76L13ednISuNS2nTmMffH2XDIWpZKDA+Cizb1blQKU32ZGPEDKUgzP8gZAvB17MKjmBGCmbA8qrI0NCXuxZEwOuZ/XEPVKs/IEmydS6OX8TVN9EzuzhByEPO1X7ipVYXmY0y1rD/4DkAcWmhvqMheYyLs26Vb7dGiSm850d6X09m6Sjplr1Ael3ZtaJNt6CrVV3VZiXhNMD/eq189sr3REZ+qO8rj8iUiLWXWacovZlHcBwDZKq7z68uAnsQ=='}], 'task': 'starting LOCAL:/Users/heikoaydt/testing/1665623714998/node/proc-repositories/727e4454c914c1fbd816c8aa2843efbdecc0c49c702a989b1c5b812eaacea73d/saasadapters/example/execute.sh'} job=Job(id='JdvkjRzM', task=Task(proc_id='727e4454c914c1fbd816c8aa2843efbdecc0c49c702a989b1c5b812eaacea73d', user_iid='byxfwaa7lp0079xe9m0os6izz0onjxe5l4ova2f7hfxlk3o7t70ug58jdoijfcgf', input=[InputReference(name='a', type='reference', obj_id='c64d6f4f11e8bd4502c0b261d360b272c17e5b52da8523cb00479611b94176d7', user_signature=None, c_hash='738ed97ed06c2de9e6fb143a8c9a99dff37b08fd410fc658a7bc65825c4f5b3f'), InputReference(name='b', type='reference', obj_id='c64d6f4f11e8bd4502c0b261d360b272c17e5b52da8523cb00479611b94176d7', user_signature=None, c_hash='738ed97ed06c2de9e6fb143a8c9a99dff37b08fd410fc658a7bc65825c4f5b3f')], output=[Output(name='c', owner_iid='byxfwaa7lp0079xe9m0os6izz0onjxe5l4ova2f7hfxlk3o7t70ug58jdoijfcgf', restricted_access=False, content_encrypted=False, target_node_iid=None)]), retain=True) reconnect=None errors=[Error(message='timeout while running job', exception=ExceptionContent(id='IB768vv2ZcQXZEEQ', reason='Error while running command', details={'reason': 'non-zero return code', 'returncode': 1, 'wrapped_command': ['bash', '-c', 'cat /Users/heikoaydt/testing/1665623714998/node/jobs/JdvkjRzM/execute_sh.pid'], 'stdout': '', 'stderr': 'cat: /Users/heikoaydt/testing/1665623714998/node/jobs/JdvkjRzM/execute_sh.pid: No such file or directory\n', 'ssh_credentials': None}))]
```

**Steps To Reproduce**
Unknown. This seems to be a race condition: when monitoring a process, files are being read (.pid and probably also others). For some reason the files don't exist yet when the read attempts happens. It seems the monitoring is faster than the process that writes the .pid file.

**Expected behaviour**
Not throwing an exception.

**Actual behaviour**
Every once in a while the execution fails.

**Comment by HeikoAydt** [comment]
Should have been fixed as part of v0.5.0. In general, the current approach has many issues. This, and related, problems are more likely to happen on NSCC which uses network file systems (afaik), increasing the risk of such things happening.
