### ISSUE TITLE
Unable to decode error JSON when sending exception details over proxy

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#362]
**Description**
When uploading data object if disk out of space, it throws a json decoding error.
This usually occurs when the expected JSON is a normal string e.g. "this is an error", missing the required "{" character.

```python
2023-07-19 02:14:03.589 [ERROR] [analysis:d77f54be60df2984d388bc55197952bb798c1f3d72f6a5129ecb6521a332fce1:district-cooling] failed -> Traceback (most recent call last):
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/saas/rest/proxy.py", line 31, in extract_response
    content = response.json()
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/explorer/analysis/base.py", line 276, in run
    results = self._analysis.perform_analysis(self._group, self._scene, self)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/duct/analyses/district_cooling.py", line 76, in perform_analysis
    bf_obj = context.sdk.upload_content(building_footprints_path, 'DUCT.GeoVectorData', 'geojson', False)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/saas/sdk/base.py", line 381, in upload_content
    meta = dor.add_data_object(content_path, self._authority.identity, access_restricted, content_encrypted,
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/saas/dor/proxy.py", line 72, in add_data_object
    result = self.post('add-c', body=body, attachment_path=content_path)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/saas/rest/proxy.py", line 246, in post
    return extract_response(response)
  File "/mnt/storage/dev/venv-servers/lib/python3.10/site-packages/saas/rest/proxy.py", line 37, in extract_response
    raise SaaSRuntimeException(response.reason, details={
saas.core.exceptions.SaaSRuntimeException: Internal Server Error
```

**Comment by reyery** [comment]
We could test if the details object can be JSON encoded in the SaaSRuntimeException` constructor and send a proper error message.
